### ISSUE TITLE
Conflict Management Dream API

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/wip-hoodie-store-on-pouchdb#32]
I see two ways to handle conflicts:

1. Conflicts can be automatically merged with app-specific logic
2. Show custom UI to have the user handle conflicts manually

## Dream API

I'll keep that updated based on the discussion in this issue.

```js
// all objects returned by all hoodie.store methods and passed
// to all events (change, add, update, remove) have a _conflicts property.

// To find all objects having a conflict, use hoodie.store.findAll with a filter function
hoodie.store.findAll(function(object) {
  return object._conflicts !== undefined;
})
.then(function(objectsWithConflicts) {
  objectsWithConflicts.forEach(function(object) {
    object._conflicts // array of conflicting versions
  })
})

// To resolve a conflict, the hoodie.store update methods accept a `removeConflicts` option.
hoodie.store.update(winningObjectVersion, {removeConflicts: true})
.then(function(newObjectVersion) {
  newObjectVersion._conflicts // undefined
});

// It can also be an array of the conflicting rev IDs or entire object
hoodie.store.update(object, {removeConflicts: [losingVersion1, losingVersion2]})

// Removing an object always automatically removes all conflicting revisions
hoodie.store.remove(object)

// You can listen to conflicts happening in the background
hoodie.store.on('change', function(object) {
  if (object._conflicts) {
    // update UI and/or handle conflict
  }
})
```

**Comment by jo** [comment]
I very much like the idea of built in merge strategies!

But I am a bit sceptical about the time based strategies, because different clients all have different times.
And we should keep in mind that in a distributed setup the conflict resolution should better happen on the server to avoid bounces.

I recently wrote a PouchDB plugin, https://github.com/jo/pouch-resolve-conflicts. Here you pass a resolve function. It would be easy to add support for build-in resolve functions.

In git there are a number of merge strategies you can use:
* `resolve` - This can only resolve two heads (i.e. the current branch and another branch you pulled from) using 3-way merge algorithm. It tries to carefully detect criss-cross merge ambiguities and is considered generally safe and fast.
* `recursive` - This can only resolve two heads using 3-way merge algorithm. When there are more than one common ancestors that can be used for 3-way merge, it creates a merged tree of the common ancestors and uses that as the reference tree for the 3-way merge. This has been reported to result in fewer merge conflicts without causing mis-merges by tests done on actual merge commits taken from Linux 2.6 kernel development history. Additionally this can detect and handle merges involving renames. This is the default merge strategy when pulling or merging one branch.
* `octopus` - This resolves more than two-head case, but refuses to do complex merge that needs manual resolution. It is primarily meant to be used for bundling topic branch heads together. This is the default merge strategy when pulling or merging more than one branches.
* `ours` - This resolves any number of heads, but the result of the merge is always the current branch head. It is meant to be used to supersede old development history of side branches.
* `subtree` - This is a modified recursive strategy. When merging trees A and B, if B corresponds to a subtree of A, B is first adjusted to match the tree structure of A, instead of reading the trees at the same level. This adjustment is also done to the common ancestor tree.

Has any of you already had a deeper look at the underlaying algorithms?

**Comment by jo** [comment]
Just found https://github.com/flitbit/diff, which can merge objects.

**Comment by janl** [comment]
Love this! Had no time to look into anything though

**Comment by gr2m** [comment]
closing in favor of https://github.com/hoodiehq/discussion/issues/87
