### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by jcw** [hoodiehq/wip-hoodie-store-on-pouchdb#49]
I was wondering how far along Hoodie is w.r.t. using PouchDB. Ongoing? On hold? Abandoned? Ready?

-jcw

**Comment by HipsterBrown** [comment]
Hi @jcw, you can watch the progress of Hoodie's migration to using PouchDB here: http://gr2m.github.io/milestones/

If you see any parts of this process you would like to help out with, we're always looking for new contributors. :smiley:

**Comment by gr2m** [comment]
@jcw it's ongoing as @HipsterBrown mentions. If you want to give a hand, here's  a good overview of open issues: http://espy.github.io/ubersicht/?showOpen=true&showClosed=false&showCommented=true&showUncommented=true&showIssues=true&showPullRequests=true&last24Hours=false&repos=hapi-couchdb-store,pouchdb-hoodie-api,pouchdb-hoodie-store,pouchdb-hoodie-sync&labels=null&milestones=null&usernames=null#hoodiehq

This repository was a proof of concept and has since been replaced by `pouchdb-hoodie-api`, `pouchdb-hoodie-sync` and `pouchdb-hoodie-store`. And `hapi-couchdb-store` gives you the new `hoodie.store` API already if you want to play with it. Next step will be the new hoodie store core plugin, then we need to make the new hoodie account core plugin (APIs defined are here: https://github.com/hoodiehq/hapi-account), and then put it all together. 

But there is A LOT of progress on this upcoming Hoodie release right now :) See https://github.com/orgs/hoodiehq/dashboard

**Comment by gr2m** [comment]
We are pretty much done with the Hoodie Store part, see https://github.com/hoodiehq/hoodie-server-store & https://github.com/hoodiehq/hoodie-client-store :) I hope we can release a pre-release version of Hoodie soon, which will integrate all the things and provide the new `hoodie.store.*` API :)
